name: badges
on:
  schedule:
    # update README badges every night
    # because we have a few badges that are linked
    # to the external repositories
    - cron: '0 3 * * *'

jobs:
  build:
    name: Badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v1

      - name: Install NPM dependencies 📦
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      # update the version of dependency-version-badge dependency
      # currently used by bahmutov/cy-rollup and bahmutov/cypress-svelte-unit-test
      - name: Update version badges from example repos 💎
        run: |
          npx update-badge \
            cypress-react-unit-test --from bahmutov/try-cra-with-unit-test --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/try-cra-app-typescript --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/react-todo-with-hooks --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/test-redux-examples --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/test-react-hooks-animations --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/test-mdx-example --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/test-apollo --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/test-xstate-react --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/test-react-router-v5 --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/test-material-ui --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/test-d3-react-gauge --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/storybook-code-coverage --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/react-loading-skeleton --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/test-swr --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/emoji-search --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/test-custom-error-boundary --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/Jscrambler-Webpack-React --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/integration-tests --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/mobx-react-typescript-boilerplate --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/test-react-hook-form --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/react-with-rollup --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/testing-react-example --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/ejected-react-scripts-example --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/react-tic-tac-toe-example --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/react-hooks-file-upload --short
          npx update-badge \
            cypress-react-unit-test --from bahmutov/react-query-example --short

      # commit any changed files
      # https://github.com/mikeal/publish-to-github-action
      - name: Push any changes to repo 📤
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
