name: badges
on:
  push:
    # update README badge only if this file changes
    branches:
      - main
    paths:
      - .github/workflows/badges.yml
  schedule:
    # update README badges every night
    # because we have a few badges that are linked
    # to the external repositories
    - cron: '0 3 * * *'

jobs:
  build:
    name: Badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v1

      - name: Install NPM dependencies 📦
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      # update the version of dependency-version-badge dependency
      # currently used by bahmutov/cy-rollup and bahmutov/cypress-svelte-unit-test
      - name: Update version badges from example repos 💎
        # note: will simplify the command when implement
        # https://github.com/bahmutov/dependency-version-badge/issues/16
        env:
          DEBUG: dependency-version-badge
        run: |
          npx update-badge \
            cypress-react-unit-test --short --behind \
            --from bahmutov/try-cra-with-unit-test \
            --from bahmutov/try-cra-app-typescript \
            --from bahmutov/react-todo-with-hooks \
            --from bahmutov/test-redux-examples \
            --from bahmutov/test-react-hooks-animations

      - name: Update more badges 💎
        run: |
          npx update-badge \
            cypress-react-unit-test --short --behind \
            --from bahmutov/test-mdx-example \
            --from bahmutov/test-apollo \
            --from bahmutov/test-xstate-react
            --from bahmutov/test-react-router-v5 \
            --from bahmutov/test-material-ui \
            --from bahmutov/test-d3-react-gauge

      - name: Update more badges 💎
        run: |
          npx update-badge \
            cypress-react-unit-test --short --behind \
            --from bahmutov/storybook-code-coverage \
            --from bahmutov/react-loading-skeleton \
            --from bahmutov/test-swr \
            --from bahmutov/emoji-search \
            --from bahmutov/test-custom-error-boundary \
            --from bahmutov/Jscrambler-Webpack-React

      - name: Update more badges 💎
        run: |
          npx update-badge \
            cypress-react-unit-test --short --behind \
            --from bahmutov/integration-tests \
            --from bahmutov/mobx-react-typescript-boilerplate \
            --from bahmutov/test-react-hook-form \
            --from bahmutov/react-with-rollup \
            --from bahmutov/testing-react-example \
            --from bahmutov/ejected-react-scripts-example \
            --from bahmutov/react-tic-tac-toe-example \
            --from bahmutov/react-hooks-file-upload \
            --from bahmutov/react-query-example

      # commit any changed files
      # https://github.com/mikeal/publish-to-github-action
      - name: Push any changes to repo 📤
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
